### ISSUE TITLE
Create a GUI app that can visual the Vectorization steps

### ISSUE THREAD

**Issue by Bobscorn** [DoubleCouponDay/Vectorizer#42]
- [x] button to step through the process 1 step at a time.

- [x] button to step backward 1 step at a time. 

- [x] Allow step buttons to run through as fast as possible, if they are held down. Must wait for 1 second before proceeding.

- [ ] have a side bar of groups/svg elements listed as text list items.

- [ ] highlight the current pixel being worked on.

- [x] click a text list item to filter the displayed elements. Display only that element.

- [x] text field to enter the step index. pressing enter after typing a valid int will run vec to that index. 
- [ ] When running vec with a step_index, write output filenames in the following format: `output{step_index}.svg`.
- [ ] if the step_index entered matches an existing output filename, render that file instead of performing the computation twice.

**Comment by DoubleCouponDay** [comment]
completed in 94608421e2aca8251f5876f81176dce6d6c67668
